Section 2
pierre-pellegrino/0 pull request #2
Opened 2021-11-21 16:35 UTC by pierre-pellegrino

Ajout de la 2è section.

Il y a probablement pas mal de changements à faire : 

 - Même si j'ai repris ta page index, mes fichiers css subsistent et je pense qu'ils n'ont plus lieu d'être
 - J'ai laissé 2 commentaires parce que je ne sais pas, pour le moment, comment accéder et modifier les fichiers sass pour rajouter du style (en l'occurrence un text-align et un justify-content:center)

Mais ça me permet comme ça de voir comment fonctionne le système de branches de git et celui de pull requests de github.

2021-11-21 19:27 UTC, Beygs requested changes
Ok c'est cool, faudra juste rajouter deux trois trucs dans le scss et supprimer les dossiers/fichiers inutiles mais sinon c'est propre !

2021-11-21 19:27 UTC, Beygs commented on index.html
> +      <!-- Manque un justify-content:center, mais pareil je ne sais pas comment toucher au sass pour le moment -->
Effectivement je te montrerai y'a rien de compliqué 😉

2021-11-21 19:27 UTC, Beygs commented on index.html
> +      </p>  Sous-titre : J'attends de voir avec toi pour intégrer le style en sass -->
Yes faudra sûrement juste rajouter une petite classe des familles dans le dossier `styles/scss/layouts/_benefits-section.scss`

2021-11-21 19:27 UTC, Beygs commented on 6f2a860e46d94afb91174aab5b126976.png:Zone.Identifier
> +HostUrl=https://fr.freelogodesign.org/manager/download/6f2a860e46d94afb91174aab5b126976
On est d'accord qu'on peut le supprimer ce fichier ?

2021-11-21 19:27 UTC, Beygs commented on index_old.html
> +<section class="herobar-whatever-section">
A supprimer

2021-11-21 19:27 UTC, Beygs commented on kit ui/index (3).html:Zone.Identifier
> +[ZoneTransfer]
Pour le dossier kit-ui je pense qu'on peut le virer aussi on l'utilise pas ici

2021-11-21 19:27 UTC, Beygs commented on navbar.css
> +.navbar-wrapper {
A supprimer (code refactorisé dans `styles/scss/layouts/_navbar.scss`

2021-11-21 19:27 UTC, Beygs commented on main.css
> +*, :before, :after {
A supprimer (code refactorisé en sass)

2021-11-23 10:38 UTC, pierre-pellegrino commented on 6f2a860e46d94afb91174aab5b126976.png:Zone.Identifier
> +HostUrl=https://fr.freelogodesign.org/manager/download/6f2a860e46d94afb91174aab5b126976
Oupsie je viens de voir tes réponses ! Ils se créent automatiquement j'ai l'impression, ça pulule dans mes dossiers... A mon avis c'est osef tiers

2021-12-06 23:18 UTC, merged